name: Playwright Tests
on:
  repository_dispatch:
    types: [test_result]
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - name: Move the index file
        run: cp playwright-report/index.html index.html
      - name: Configure Git
        run: |
          git config --global user.email "karinavu.january@gmail.com"
          git config --global user.name "Karina's Bot"
      - name: Commit changed files
        run: |
          git add .
          git commit -m "Auto-update report"
      - name: Push to master
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          git remote set-url origin https://github.com/${{ github.repository }}.git
          git push origin HEAD:main
